## Base image
FROM ubuntu

## Dockerfile author
MAINTAINER Johannes Luther <joe@netgab.net>

## Install packages and dependencies
RUN apt-get update && apt-get install -y \
      freeradius \
      openssl && \
      rm -rf /var/lib/apt/lists/*

EXPOSE \
    1812/udp \
    1813/udp

CMD ["freeradius","-fxX"]
